// <auto-generated />
namespace BELibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Add_New_Table_Doctor_Faculty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_New_Table_Doctor_Faculty));
        
        string IMigrationMetadata.Id
        {
            get { return "202005160953071_Add_New_Table_Doctor_Faculty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
